@JWT = eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNzI0MzkzODY4LCJleHAiOjE3MjQzOTc0Njh9.OrBwJaAey3ID_fqc3I7fzh3kgWZS5wI5SLBZpEAtMsQ

###############################################################
###################### Authentication #########################
###############################################################
### Sign up
POST http://localhost:8080/signup
Content-Type: application/json

{
  "username": "user1",
  "profileName": "user profile",
  "password": "asdfasdf1234"
}

###############################################################
### Log in
POST http://localhost:8080/login
Content-Type: multipart/form-data; boundary=boundary_string

--boundary_string
Content-Disposition: form-data; name="username"

user1

--boundary_string
Content-Disposition: form-data; name="password"

asdfasdf1234
--boundary_string

###############################################################
### Log out
POST http://localhost:8080/logout
Authorization: Bearer {{JWT}}



###############################################################
###################### Bulletin Board #########################
###############################################################
### Get BulletinBoard List
GET http://localhost:8080/bulletinBoard
Authorization: Bearer {{JWT}}
Content-Type: application/json

###############################################################
### Post BulletinBoard
POST http://localhost:8080/bulletinBoard
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
  "title": "Hello",
  "content": "Content hello",
  "author": "me",
  "password": "pw"
}

###############################################################
### Put BulletinBoard
PUT http://localhost:8080/bulletinBoard/1
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
  "title": "Hello",
  "content": "Content hello Changed",
  "author": "me",
  "password": "pw"
}

###############################################################
### Delete BulletinBoard
DELETE http://localhost:8080/bulletinBoard/2
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
  "password": "pw"
}

###############################################################
########################### Reply #############################
###############################################################
POST http://localhost:8080/bulletinBoard/1/reply
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
  "content": "Content Hello"
}